### ISSUE TITLE
healer.exe not exists ?

### ISSUE THREAD

**Issue by mehdighninoudev** [hac425xxx/trapfuzzer#2]
Hi, I have configured the config.json for the fuzzer but when I run trap_fuzzer.py with python 2.7 I got this error : healer.exe not exists!

Where to find healer.exe ? please ?

**Comment by hac425xxx** [comment]
binary
https://github.com/hac425xxx/trapfuzzer-windows-agent/releases/tag/2021-11-17

source code
https://github.com/hac425xxx/trapfuzzer-windows-agent

**Comment by mehdighninoudev** [comment]
understood thank you for support sir

**Comment by mehdighninoudev** [comment]
When I execute `python trap_fuzzer.py` I got this error:
CreateProcess failed, 0x80070002
Traceback (most recent call last):
  File "trap_fuzzer.py", line 1033, in <module>
    fuzzer.fuzz()
  File "trap_fuzzer.py", line 890, in fuzz
    self.load_testcase(self.config['testcase'])
  File "trap_fuzzer.py", line 782, in load_testcase
    ret = self.exec_testcase(self.patch_to_binary)
  File "trap_fuzzer.py", line 872, in exec_testcase
    return self.tracer.trace(need_patch_to_file, verbose, self.exit_basci_block, timeout)
  File "C:\Users\User\Desktop\Tools\Fuzzing\coverage_fuzzing\trapfuzzer\tracer\WindbgExtTracer.py", line 108, in trace
    data = struct.unpack("<I", self.client_sock.recv(4))[0]
socket.error: [Errno 10054] An existing connection had to be closed by the remote host

How to resolve the problem please ?
